FROM docker.bintray.io/jfrog/artifactory-pro:5.2.1

MAINTAINER eldada@jfrog.com

# Download the DB driver into Tomcat's lib
RUN curl -L -o /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.2.10.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.2.10/mysql-connector-java-5.2.10.jar

