FROM docker.bintray.io/jfrog/artifactory-pro:5.1.2

MAINTAINER eldada@jfrog.com

# Download the DB driver into Tomcat's lib
RUN curl -o /opt/jfrog/artifactory/tomcat/lib/postgresql-9.4.1212.jar https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar

