FROM docker.bintray.io/jfrog/artifactory-pro:6.20.0

MAINTAINER eldada@jfrog.com

# Download the DB driver into Tomcat's lib
RUN wget -O /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.41.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar
